### ISSUE TITLE
Add additional jansson constraints

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-spack#8]
flux-core versions 0.21+ require jansson 2.10+: https://github.com/flux-framework/flux-core/commit/a6086e021ee9bf869663bc475d4311dc540486fe

**Comment by vsoch** [comment]
@SteVwonder can we close this? I'm assuming this is old, but let me know if this still needs to be done (with some guidance I can take a look!)

**Comment by SteVwonder** [comment]
Yeah, looks like it was added already. Safe to close :)
